version: '3.9'
services:
  nginx:
    container_name: proxy
    restart: on-failure
    image: nginx:latest
    volumes:
      - ./nginx/prod/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/api/static
    ports:
      - "80:80"
    depends_on:
      - web
  web:
    container_name: backend
    build: .
    restart: always
    env_file: prod.env
    command: gunicorn Core.wsgi:application --bind 0.0.0.0:5000
    volumes:
     - .:/api
     - static_volume:/api/static
    depends_on:
     - db
  db:
    container_name: database
    image: postgres:12-alpine3.15
    env_file: prod.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  static_volume:
  postgres_data:
